## Analise exploratoria Daquiprafora

In [80]:
import pandas as pd
import seaborn as sns # evite fazer pairplot! Estoura a memória
import statsmodels.api as sm
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import expon, binom, t, norm, probplot, scoreatpercentile, percentileofscore
%matplotlib inline
import sklearn.model_selection as sk
import sklearn.linear_model as skl
import sklearn as sklearn
import sklearn.metrics as skm
import statsmodels.api as sm

In [12]:
compilado = pd.read_excel('Desistências.xlsx')

In [91]:
def master_function_xxx (x):
    if x == "D":
        return 1
    else:
        return 0

In [92]:
compilado

,Data,Nome,Desistências,Países:,Clima,Frase,Cidade,Tamanho,Esportes,RANKING,...,9_Urbano,9_Praia,9_Montanha,9_Campo,10_Qualidade_Acadêmica,10_RANKING,10_Custo,10_CLIMA,10_LOCALIZAÇÃO,10_ESPORTE
0,2018-04-11 21:17:20.003,Aline Ribeiro Chaves,S,EUA,1,1,4,1,4,1,...,1,2,2,2,1,2,1,3,2,3
1,2018-07-04 15:41:47.167,Allan Maia Serapiao,S,"EUA, UK",3,3,2,3,2,2,...,3,4,1,2,1,2,2,3,3,3
2,2019-01-09 12:18:25.847,Amanda Jacobovicz,S,EUA,1,2,3,1,2,1,...,4,1,2,3,1,2,2,2,2,3
3,2018-10-08 22:34:15.506,Amanda Sondermann Carneiro,S,"Canada, EUA",4,3,3,3,2,2,...,3,2,1,3,1,2,3,3,2,3
4,2018-09-20 04:22:10.691,Ana Carolina Abtibol Ramos,S,"Canada, EUA, UK",1,1,3,2,2,2,...,3,1,2,4,2,3,3,3,3,3
5,2018-04-03 18:55:14.604,Ana Laura Pafaro Costa e Silva,S,"Canada, EUA",3,2,2,2,4,2,...,1,4,3,2,2,3,1,3,3,3
6,2018-08-12 17:52:26.099,André Gonçalves Brunner,D,"Canada, EUA, UK",1,1,4,3,2,1,...,2,4,2,3,1,2,1,3,2,3
7,2018-02-28 23:55:59.588,André Gontijo Perez de Queiroz,D,"Canada, EUA, UK",2,1,3,1,1,2,...,3,1,2,2,2,2,3,3,3,1
8,2018-12-04 16:30:44.401,Anita Brígida Cipriano Goes Guimarães,S,"Canada, EUA",1,2,2,3,3,2,...,2,2,1,1,1,3,1,3,2,3
9,2018-03-21 15:28:58.947,Arthur antoneli hans,S,EUA,4,2,4,1,3,2,...,2,1,3,2,1,3,3,3,3,3
10,2018-09-07 14:15:44.074,Arthur Wisintainer Cavinato,S,"Canada, EUA",3,3,3,1,1,2,...,2,2,1,3,1,3,1,3,3,3
11,2018-10-22 23:47:51.187,Artur Brito Neri Souza,S,"EUA, UK",3,2,4,1,4,2,...,3,3,4,4,2,3,2,3,2,3
12,2018-04-11 22:05:08.785,Beatriz Neves Carvalho Pinto,S,"Canada, UK",3,1,3,2,2,2,...,1,2,3,2,2,3,2,3,1,3
13,2018-04-09 17:15:09.993,Bruna Sapiro,S,"EUA, UK",1,4,3,2,4,2,...,1,1,2,4,1,2,3,3,2,3
14,2018-04-03 18:52:28.966,Camila Bellomo Carrieri,S,EUA,2,1,2,1,1,4,...,1,1,3,3,1,3,2,1,1,3
15,2018-05-19 15:46:23.758,Camila Vaz Areal,D,"EUA, UK",1,2,4,3,2,1,...,1,1,2,3,1,2,1,3,2,3
16,2018-08-17 12:21:25.930,Carlos Theophilo Bandeira de Mello Azeredo Santos,S,EUA,1,1,3,2,2,3,...,2,1,3,4,1,2,3,3,2,3
17,2018-03-21 18:01:41.217,Carolina Fleck dos Reis lara,S,EUA,4,4,4,1,2,1,...,1,1,2,2,1,1,3,3,3,3
18,2018-03-08 17:36:49.025,Carolina Klauck Novaes,S,"Canada, EUA",1,4,3,2,2,2,...,2,3,2,3,1,3,1,3,2,3
19,2018-03-24 22:13:39.716,Catarina de Albuquerque Ferraz,S,EUA,2,4,4,1,2,3,...,3,1,2,2,1,3,3,3,3,3
20,2018-08-03 13:31:13.799,Clara Faria Hirata,S,"Canada, EUA",4,2,4,1,2,3,...,1,1,1,1,1,3,1,3,3,3
21,2018-03-22 19:43:22.438,Clara Ribeiro Betancourt,S,"Canada, EUA",2,1,3,1,1,2,...,1,1,2,3,2,2,3,3,2,2
22,2018-05-15 20:35:47.887,Clara Zioli da Igreja,S,"Canada, EUA, UK",1,4,1,1,2,2,...,3,2,1,1,1,2,1,3,3,3
23,2018-05-23 16:58:11.681,Daniela Sampaio Cabraitz,S,EUA,1,2,2,3,2,2,...,2,1,2,2,1,2,2,3,3,3
24,2018-10-10 09:46:01.841,David Ivan Barba Zamora,S,"Canada, EUA",3,3,1,1,2,2,...,3,2,1,1,1,3,2,3,3,3
25,2018-03-27 19:59:39.563,Diego Cardenas,S,EUA,1,2,1,3,1,2,...,3,1,1,3,1,2,1,2,3,2
26,2018-11-01 20:06:03.111,Dyllan Ferreira Durço Lomba,S,"Canada, EUA, UK",1,2,4,1,2,3,...,2,2,2,2,3,3,3,3,2,2
27,2018-06-10 11:36:40.282,EDUARDA RAFAELI KOTLINSKY DOS SANTOS,S,Canada,1,2,3,1,2,2,...,1,1,2,2,1,1,1,3,3,3
28,2018-09-03 18:08:04.430,Eduardo Valandro Moutinho,S,EUA,4,2,4,3,2,2,...,1,3,2,4,3,3,1,3,3,2
29,2019-01-14 12:37:38.561,Enzo Araújo Tassini,S,EUA,4,2,3,1,3,1,...,2,1,3,4,1,3,1,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2018-03-26 20:15:42.653,Pedro Duarte Moreira,S,EUA,4,4,3,1,2,1,...,2,2,2,2,1,1,1,3,2,3
120,2018-02-28 19:12:33.497,Pedro Mattos de Senna e Silva,S,EUA,4,4,3,1,2,1,...,1,2,1,3,1,2,3,3,3,3
121,2018-09-27 17:11:17.088,Pedro Nepomuceno de Carvalho,S,EUA,1,2,2,3,2,1,...,3,1,3,3,1,1,2,2,2,3
122,2018-09-15 12:37:35.676,Rafael Anargyrou,S,"Canada, EUA",1,2,3,1,1,3,...,1,1,1,2,1,3,3,3,1,2
123,2018-02-28 18:06:24.906,Rafael Brum Marcondes,S,UK,1,3,4,1,2,2,...,2,4,3,2,1,3,2,3,3,3
124,2018-04-30 11:51:28.907,Raphael Viana Curvelo Sepúlvida,D,"Canada, EUA",1,1,2,1,3,2,...,3,2,3,3,1,2,2,3,3,3
125,2018-04-28 18:44:44.102,Raquel Jorge Fernandes,S,EUA,1,2,3,1,3,2,...,1,1,2,2,1,1,2,3,2,3
126,2018-07-16 18:28:08.100,Renan Kenji Kashin Ogasawara,S,"EUA, UK",2,1,3,3,1,2,...,3,1,2,2,1,2,2,2,1,1
127,2018-10-24 20:00:52.159,Renato Granja Guiguet Leal,D,EUA,4,3,4,1,4,1,...,2,2,2,2,1,1,1,3,3,3
128,2018-07-25 13:19:56.407,Rene Korehisa Martinez,S,EUA,4,1,3,1,1,1,...,1,1,1,2,1,3,1,3,2,3
129,2018-07-26 09:13:48.500,Rene Korehisa Martinez,S,EUA,4,4,3,1,1,1,...,1,1,1,2,1,1,1,3,3,3
130,2018-09-28 10:44:05.365,Roberta Szabo Ponce,S,Canada,1,2,4,1,2,2,...,3,4,3,3,1,2,2,2,3,3
131,2018-10-21 17:42:52.898,Sarah de Castro Lobato Vaz Machado,S,EUA,4,2,2,1,1,1,...,1,1,2,3,1,2,3,3,2,3
132,2018-05-24 11:19:24.447,Sofia de Castro Portugal Andrade,S,EUA,1,2,4,2,1,2,...,3,1,2,2,1,2,1,1,2,3
133,2018-07-04 17:19:57.951,Sophia De Andrade Simon,S,"Canada, EUA, UK",4,2,3,3,2,3,...,1,1,2,3,1,3,2,3,2,3
134,2018-09-07 15:14:07.922,Tadeu Lopes Matos,S,"Canada, EUA",4,4,3,3,1,2,...,3,2,2,2,1,2,1,3,2,3
135,2018-04-03 22:36:46.198,Tales Foryta Jacoski,S,"Canada, EUA",4,1,3,1,1,2,...,2,1,2,4,1,2,1,3,3,2
136,2018-03-09 18:20:52.261,Thais Mitsuda Chagas,S,"Canada, EUA",1,1,3,3,2,3,...,1,1,2,4,1,3,1,1,1,3
137,2018-03-01 22:10:59.092,Valentina Rosset,S,EUA,1,1,3,2,3,2,...,1,2,2,2,2,3,3,3,2,3
138,2018-03-06 20:23:46.381,Victor Haysser Nardini Simões,S,"Canada, EUA, UK",4,2,3,1,2,1,...,1,2,3,4,1,1,3,3,2,3
139,2018-10-24 17:32:26.830,Victoria de Assis Torrentes,S,"Canada, EUA, UK",4,1,3,2,3,3,...,1,1,4,2,1,3,1,3,2,3
140,2018-08-14 10:54:42.289,Vinicius Gabriel Angelozzi Verona de Resende,S,"Canada, EUA, UK",1,1,4,1,2,2,...,3,2,1,1,1,2,1,3,2,2
141,2018-06-10 21:55:52.714,Vinícius Martins Ouverney dos Santos,S,"Canada, EUA",4,4,4,1,2,2,...,2,2,3,3,1,1,2,3,1,2
142,2018-05-15 16:41:47.957,Vitor Magalhães Lamego,D,"Canada, EUA",1,1,3,1,1,2,...,1,1,3,4,1,1,1,1,1,2
143,2018-08-02 16:49:03.856,Vitor Minami Chiga,S,"Canada, EUA",4,2,3,2,3,2,...,1,3,2,4,1,2,3,3,2,3
144,2018-04-26 14:16:14.843,Vitória Ibias Flach,S,"Canada, EUA, UK",1,1,1,1,2,3,...,1,1,4,4,2,3,1,2,1,3
145,2018-11-06 14:21:30.716,Vitória Mendonça Siqueira,D,"Canada, EUA",1,1,2,1,2,3,...,2,1,3,4,1,3,1,3,3,3
146,2018-12-21 12:48:22.525,Vitoria Rodrigues Castillo,S,EUA,2,1,1,2,2,2,...,2,1,3,4,2,2,2,2,2,2
147,2018-10-04 12:24:20.272,Waldemar . Verdi Netto,S,"EUA, UK",1,1,3,3,2,2,...,2,1,1,2,2,3,3,1,2,3
148,2018-03-20 15:57:22.933,Xiao Yi Song,S,"Canada, EUA",1,1,3,1,2,3,...,1,1,3,4,1,3,1,2,3,3

In [93]:
compilado["Desistências"] = compilado["Desistências"].apply(master_function_xxx)

In [94]:
def classificador(x):
    if x == "Gosto de ter contato com climas diferentes em épocas diferentes. Não quero viver apenas no calor ou apenas no frio" | "Gosto de ter muitas opções de atividades. Adoro museus, shows, e lugares diferentes" | "Paisagens lindas, florestas, e fácil acesso à natureza" | 'Quero sempre ter alguém novo para conhecer. Quero aproveitar toda a infraestrutura que uma grande faculdade pode oferecer' | "Poderia assistir todas as competições ao vivo se fosse possível" | "Só quero faculdades com bons Rankings. Ponto final" | "Ficar em casa mexendo no computador, jogando vídeo games, ou lendo livros" | "Oportunidades de fazer pesquisa significante com professores" | "Amo!" | "Extremamente Importante":
        return 1
    elif x == "Odeio o frio e prefiro ficar em lugares quentes" | "Estou muito animado(a) para aproveitar tudo que meu campus oferece, incluindo student clubs, shows que trazem para campus, e conversando com meus novos amigos até a madrugada dentro de nosso dormitório" | "Uma cidade menor, muito animada, com tudo que precisa perto" | "Imagino um campus onde eu posso andar por um lado ao outro em menos de 30 minutos. Quero ter uma mistura de aulas enormes de mais de 100 alunos e outros menores de menos de 20" | "Não sou uma mega fã, mais gosto de assistir de vez em quando" | "A qualidade do curso é mais importante do que nome na meu diploma" | "Fico com alguns amigos mais íntimos" | "Aprender um pouco sobre vários assuntos e me desenvolver mais pessoalmente" | "Poderia ser divertido" | "Importante":
        return 2
    elif x == "Eu preferia ficar em lugares mais frios" | "No Campus, meu lugar favorito será a biblioteca, os laboratórios e as salas de aula e meu quarto no dormitório" | "Imagino um campus onde eu conheceria a maioria dos alunos, pelo menos de vista. Gostaria de conhecer meus professores muito bem, me sinto bem em ambientes mais intimas onde pessoas lembram seu nome" | "Esportes? Prefiro assistir Netflix" | "Para mim a melhor faculdade é onde posso entrar e ser feliz" | "Faço algum tipo de atividade física" | "Uma seleção enorme de aulas diferentes" | "Interessante" | "Relativamente Importante":
        return 3
    elif x == "Não tenho preferência" | "Local cosmopolita, lotado com muita gente, e várias culturas diferentes" | "Não é relevante" | "Ir para festas super animadas" | "Um diploma super prático que me permita trabalhar diretamente depois de graduação" | "Não gostaria" | "Pouco Importante":
        return 4
    elif x == "Indiferente" | "Sem Importante":
        return 5

In [99]:
Y = compilado["Desistências"]
X = compilado.drop(["Desistências","Data","Nome", "Países:"], axis = 1)

In [100]:
X_train, X_test, Y_train, Y_test=sk.train_test_split(X,Y,test_size=0.25,random_state=0)

In [101]:
X_train.head()

,Clima,Frase,Cidade,Tamanho,Esportes,RANKING,Tempo_Livre,FOCO,9_Urbano,9_Praia,9_Montanha,9_Campo,10_Qualidade_Acadêmica,10_RANKING,10_Custo,10_CLIMA,10_LOCALIZAÇÃO,10_ESPORTE
51,1,1,1,3,2,2,2,4,2,1,2,2,2,3,1,3,2,3
2,1,2,3,1,2,1,4,4,4,1,2,3,1,2,2,2,2,3
146,2,1,1,2,2,2,2,2,2,1,3,4,2,2,2,2,2,2
10,3,3,3,1,1,2,1,1,2,2,1,3,1,3,1,3,3,3
56,4,4,4,1,1,2,1,1,2,2,2,2,1,1,1,3,3,3

In [102]:
logrer = skl.LogisticRegression()

In [103]:
result=logrer.fit(X_train,Y_train)

C:\Users\Felipe Germanos\Documents\Python\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [104]:
Y_pred= logrer.predict(X_test)

In [105]:
matrix = skm.confusion_matrix(Y_test, Y_pred)

In [106]:
matrix

array([[36,  0],
       [ 2,  0]], dtype=int64)

In [107]:
skm.accuracy_score(Y_test, Y_pred)

0.9473684210526315

In [108]:
result

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [109]:
result.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'max_iter': 100,
 'multi_class': 'warn',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'warn',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [110]:
result.decision_function()

TypeError: decision_function() missing 1 required positional argument: 'X'

In [111]:
X_train

,Clima,Frase,Cidade,Tamanho,Esportes,RANKING,Tempo_Livre,FOCO,9_Urbano,9_Praia,9_Montanha,9_Campo,10_Qualidade_Acadêmica,10_RANKING,10_Custo,10_CLIMA,10_LOCALIZAÇÃO,10_ESPORTE
51,1,1,1,3,2,2,2,4,2,1,2,2,2,3,1,3,2,3
2,1,2,3,1,2,1,4,4,4,1,2,3,1,2,2,2,2,3
146,2,1,1,2,2,2,2,2,2,1,3,4,2,2,2,2,2,2
10,3,3,3,1,1,2,1,1,2,2,1,3,1,3,1,3,3,3
56,4,4,4,1,1,2,1,1,2,2,2,2,1,1,1,3,3,3
113,4,1,4,2,4,2,2,2,1,2,2,2,1,2,2,3,3,3
143,4,2,3,2,3,2,1,4,1,3,2,4,1,2,3,3,2,3
116,4,4,4,3,2,1,2,4,1,1,1,1,1,1,1,3,3,3
66,2,1,3,3,1,2,2,4,2,1,3,4,2,2,1,2,3,1
78,1,2,3,2,3,2,1,4,1,4,4,4,1,2,1,3,1,3
71,3,4,2,3,1,2,2,4,1,3,2,4,1,3,1,2,2,3
131,4,2,2,1,1,1,4,2,1,1,2,3,1,2,3,3,2,3
120,4,4,3,1,2,1,1,2,1,2,1,3,1,2,3,3,3,3
89,1,2,3,3,2,2,2,2,1,3,2,4,2,3,1,3,2,3
145,1,1,2,1,2,3,1,1,2,1,3,4,1,3,1,3,3,3
100,1,2,3,1,2,2,2,2,1,1,3,4,1,3,3,3,3,3
50,1,3,4,1,3,3,2,3,1,3,1,2,2,2,2,3,3,3
126,2,1,3,3,1,2,4,4,3,1,2,2,1,2,2,2,1,1
60,1,1,3,2,1,2,2,2,1,2,3,4,1,2,3,3,2,2
30,2,1,3,1,1,2,2,4,1,2,1,3,2,3,1,1,2,2
63,1,4,2,2,4,3,2,1,2,2,2,2,3,3,3,3,3,3
91,1,1,3,1,3,3,4,2,1,1,2,4,1,2,2,3,1,3
83,2,1,4,1,2,1,4,1,1,1,2,2,2,3,1,1,2,2
86,1,2,2,3,2,3,3,4,1,1,2,3,2,3,1,3,3,3
123,1,3,4,1,2,2,1,1,2,4,3,2,1,3,2,3,3,3
98,1,2,1,2,2,2,3,2,1,1,2,3,1,2,2,3,3,3
122,1,2,3,1,1,3,4,2,1,1,1,2,1,3,3,3,1,2
48,4,1,3,2,3,2,4,2,3,2,4,4,1,3,3,3,1,3
13,1,4,3,2,4,2,2,4,1,1,2,4,1,2,3,3,2,3
108,3,4,3,2,2,2,1,4,3,4,2,4,3,3,3,3,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,2,4,4,1,2,3,4,3,3,1,2,2,1,3,3,3,3,3
29,4,2,3,1,3,1,2,1,2,1,3,4,1,3,1,3,3,3
129,4,4,3,1,1,1,4,4,1,1,1,2,1,1,1,3,3,3
49,2,1,3,1,1,1,4,2,2,1,3,3,1,2,1,3,3,1
135,4,1,3,1,1,2,2,1,2,1,2,4,1,2,1,3,3,2
99,2,1,4,1,3,2,1,4,2,4,1,1,1,3,2,1,1,3
82,3,3,3,2,1,2,3,4,3,2,1,2,1,2,3,3,3,3
64,1,2,2,1,1,2,1,3,1,4,4,4,1,3,1,1,1,1
148,1,1,3,1,2,3,1,2,1,1,3,4,1,3,1,2,3,3
79,1,1,2,2,2,3,2,2,1,1,1,1,2,2,2,3,3,3
115,2,1,3,3,4,2,2,4,1,2,3,4,1,2,2,3,2,3
144,1,1,1,1,2,3,2,4,1,1,4,4,2,3,1,2,1,3
72,1,2,2,2,1,2,2,4,1,1,2,2,1,1,2,2,2,1
77,2,1,3,1,4,2,3,3,2,1,4,4,1,3,3,2,1,3
25,1,2,1,3,1,2,2,2,3,1,1,3,1,2,1,2,3,2
81,1,1,4,1,2,2,3,4,1,1,3,2,1,2,3,3,2,3
139,4,1,3,2,3,3,2,2,1,1,4,2,1,3,1,3,2,3
141,4,4,4,1,2,2,1,1,2,2,3,3,1,1,2,3,1,2
39,4,4,4,2,2,2,4,1,2,4,2,2,2,2,2,3,3,3
58,1,2,3,1,1,2,4,2,1,1,2,4,1,1,1,3,2,2
88,1,2,3,1,1,2,2,3,1,1,3,2,1,2,2,2,2,1
70,1,4,3,1,4,2,2,4,3,1,3,3,1,2,1,2,1,3
87,3,1,3,3,2,2,2,2,1,3,3,2,1,2,3,3,1,3
36,1,1,3,1,2,1,1,4,1,2,3,1,2,2,1,3,2,3
21,2,1,3,1,1,2,3,2,1,1,2,3,2,2,3,3,2,2
9,4,2,4,1,3,2,1,2,2,1,3,2,1,3,3,3,3,3
103,2,1,2,1,1,2,3,2,2,1,1,3,1,2,2,2,3,1
67,1,1,3,1,1,2,2,2,1,3,4,4,2,2,2,2,1,2
117,4,2,4,1,1,1,3,2,2,2,1,4,1,3,3,3,2,2
47,1,2,3,1,2,3,1,2,1,4,3,3,2,2,2,2,1,3

In [120]:
X = result.coef_[0
            ]

array([-0.60229923, -0.18973014,  0.33542357,  0.10074163,  0.28544304,
        0.00986265, -0.60814964,  0.25050886,  0.36659552, -0.14137997,
       -0.4852885 , -0.13485833, -0.3661932 , -1.04505627, -0.21648425,
        0.22387284,  0.69051494,  0.02174776])

In [121]:
def sigmoid (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r):
    x = ((-0.60229923*a) + (-0.18973014*b) + 0.33542357*c + 0.10074163*d + 0.28544304*e +
        0.00986265*f + (-0.60814964*g) + 0.25050886*h + 0.36659552*i + (-0.14137997*j) + (-0.4852885*k) + (-0.13485833*l) + (-0.3661932*m) + (-1.04505627*n) + (-0.21648425*o)
+ 0.22387284*p + 0.69051494*q + 0.02174776*r)
    y = 1/(1+np.exp(-x))
    return y

In [124]:
compilado

,Data,Nome,Desistências,Países:,Clima,Frase,Cidade,Tamanho,Esportes,RANKING,...,9_Urbano,9_Praia,9_Montanha,9_Campo,10_Qualidade_Acadêmica,10_RANKING,10_Custo,10_CLIMA,10_LOCALIZAÇÃO,10_ESPORTE
0,2018-04-11 21:17:20.003,Aline Ribeiro Chaves,0,EUA,1,1,4,1,4,1,...,1,2,2,2,1,2,1,3,2,3
1,2018-07-04 15:41:47.167,Allan Maia Serapiao,0,"EUA, UK",3,3,2,3,2,2,...,3,4,1,2,1,2,2,3,3,3
2,2019-01-09 12:18:25.847,Amanda Jacobovicz,0,EUA,1,2,3,1,2,1,...,4,1,2,3,1,2,2,2,2,3
3,2018-10-08 22:34:15.506,Amanda Sondermann Carneiro,0,"Canada, EUA",4,3,3,3,2,2,...,3,2,1,3,1,2,3,3,2,3
4,2018-09-20 04:22:10.691,Ana Carolina Abtibol Ramos,0,"Canada, EUA, UK",1,1,3,2,2,2,...,3,1,2,4,2,3,3,3,3,3
5,2018-04-03 18:55:14.604,Ana Laura Pafaro Costa e Silva,0,"Canada, EUA",3,2,2,2,4,2,...,1,4,3,2,2,3,1,3,3,3
6,2018-08-12 17:52:26.099,André Gonçalves Brunner,1,"Canada, EUA, UK",1,1,4,3,2,1,...,2,4,2,3,1,2,1,3,2,3
7,2018-02-28 23:55:59.588,André Gontijo Perez de Queiroz,1,"Canada, EUA, UK",2,1,3,1,1,2,...,3,1,2,2,2,2,3,3,3,1
8,2018-12-04 16:30:44.401,Anita Brígida Cipriano Goes Guimarães,0,"Canada, EUA",1,2,2,3,3,2,...,2,2,1,1,1,3,1,3,2,3
9,2018-03-21 15:28:58.947,Arthur antoneli hans,0,EUA,4,2,4,1,3,2,...,2,1,3,2,1,3,3,3,3,3
10,2018-09-07 14:15:44.074,Arthur Wisintainer Cavinato,0,"Canada, EUA",3,3,3,1,1,2,...,2,2,1,3,1,3,1,3,3,3
11,2018-10-22 23:47:51.187,Artur Brito Neri Souza,0,"EUA, UK",3,2,4,1,4,2,...,3,3,4,4,2,3,2,3,2,3
12,2018-04-11 22:05:08.785,Beatriz Neves Carvalho Pinto,0,"Canada, UK",3,1,3,2,2,2,...,1,2,3,2,2,3,2,3,1,3
13,2018-04-09 17:15:09.993,Bruna Sapiro,0,"EUA, UK",1,4,3,2,4,2,...,1,1,2,4,1,2,3,3,2,3
14,2018-04-03 18:52:28.966,Camila Bellomo Carrieri,0,EUA,2,1,2,1,1,4,...,1,1,3,3,1,3,2,1,1,3
15,2018-05-19 15:46:23.758,Camila Vaz Areal,1,"EUA, UK",1,2,4,3,2,1,...,1,1,2,3,1,2,1,3,2,3
16,2018-08-17 12:21:25.930,Carlos Theophilo Bandeira de Mello Azeredo Santos,0,EUA,1,1,3,2,2,3,...,2,1,3,4,1,2,3,3,2,3
17,2018-03-21 18:01:41.217,Carolina Fleck dos Reis lara,0,EUA,4,4,4,1,2,1,...,1,1,2,2,1,1,3,3,3,3
18,2018-03-08 17:36:49.025,Carolina Klauck Novaes,0,"Canada, EUA",1,4,3,2,2,2,...,2,3,2,3,1,3,1,3,2,3
19,2018-03-24 22:13:39.716,Catarina de Albuquerque Ferraz,0,EUA,2,4,4,1,2,3,...,3,1,2,2,1,3,3,3,3,3
20,2018-08-03 13:31:13.799,Clara Faria Hirata,0,"Canada, EUA",4,2,4,1,2,3,...,1,1,1,1,1,3,1,3,3,3
21,2018-03-22 19:43:22.438,Clara Ribeiro Betancourt,0,"Canada, EUA",2,1,3,1,1,2,...,1,1,2,3,2,2,3,3,2,2
22,2018-05-15 20:35:47.887,Clara Zioli da Igreja,0,"Canada, EUA, UK",1,4,1,1,2,2,...,3,2,1,1,1,2,1,3,3,3
23,2018-05-23 16:58:11.681,Daniela Sampaio Cabraitz,0,EUA,1,2,2,3,2,2,...,2,1,2,2,1,2,2,3,3,3
24,2018-10-10 09:46:01.841,David Ivan Barba Zamora,0,"Canada, EUA",3,3,1,1,2,2,...,3,2,1,1,1,3,2,3,3,3
25,2018-03-27 19:59:39.563,Diego Cardenas,0,EUA,1,2,1,3,1,2,...,3,1,1,3,1,2,1,2,3,2
26,2018-11-01 20:06:03.111,Dyllan Ferreira Durço Lomba,0,"Canada, EUA, UK",1,2,4,1,2,3,...,2,2,2,2,3,3,3,3,2,2
27,2018-06-10 11:36:40.282,EDUARDA RAFAELI KOTLINSKY DOS SANTOS,0,Canada,1,2,3,1,2,2,...,1,1,2,2,1,1,1,3,3,3
28,2018-09-03 18:08:04.430,Eduardo Valandro Moutinho,0,EUA,4,2,4,3,2,2,...,1,3,2,4,3,3,1,3,3,2
29,2019-01-14 12:37:38.561,Enzo Araújo Tassini,0,EUA,4,2,3,1,3,1,...,2,1,3,4,1,3,1,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2018-03-26 20:15:42.653,Pedro Duarte Moreira,0,EUA,4,4,3,1,2,1,...,2,2,2,2,1,1,1,3,2,3
120,2018-02-28 19:12:33.497,Pedro Mattos de Senna e Silva,0,EUA,4,4,3,1,2,1,...,1,2,1,3,1,2,3,3,3,3
121,2018-09-27 17:11:17.088,Pedro Nepomuceno de Carvalho,0,EUA,1,2,2,3,2,1,...,3,1,3,3,1,1,2,2,2,3
122,2018-09-15 12:37:35.676,Rafael Anargyrou,0,"Canada, EUA",1,2,3,1,1,3,...,1,1,1,2,1,3,3,3,1,2
123,2018-02-28 18:06:24.906,Rafael Brum Marcondes,0,UK,1,3,4,1,2,2,...,2,4,3,2,1,3,2,3,3,3
124,2018-04-30 11:51:28.907,Raphael Viana Curvelo Sepúlvida,1,"Canada, EUA",1,1,2,1,3,2,...,3,2,3,3,1,2,2,3,3,3
125,2018-04-28 18:44:44.102,Raquel Jorge Fernandes,0,EUA,1,2,3,1,3,2,...,1,1,2,2,1,1,2,3,2,3
126,2018-07-16 18:28:08.100,Renan Kenji Kashin Ogasawara,0,"EUA, UK",2,1,3,3,1,2,...,3,1,2,2,1,2,2,2,1,1
127,2018-10-24 20:00:52.159,Renato Granja Guiguet Leal,1,EUA,4,3,4,1,4,1,...,2,2,2,2,1,1,1,3,3,3
128,2018-07-25 13:19:56.407,Rene Korehisa Martinez,0,EUA,4,1,3,1,1,1,...,1,1,1,2,1,3,1,3,2,3
129,2018-07-26 09:13:48.500,Rene Korehisa Martinez,0,EUA,4,4,3,1,1,1,...,1,1,1,2,1,1,1,3,3,3
130,2018-09-28 10:44:05.365,Roberta Szabo Ponce,0,Canada,1,2,4,1,2,2,...,3,4,3,3,1,2,2,2,3,3
131,2018-10-21 17:42:52.898,Sarah de Castro Lobato Vaz Machado,0,EUA,4,2,2,1,1,1,...,1,1,2,3,1,2,3,3,2,3
132,2018-05-24 11:19:24.447,Sofia de Castro Portugal Andrade,0,EUA,1,2,4,2,1,2,...,3,1,2,2,1,2,1,1,2,3
133,2018-07-04 17:19:57.951,Sophia De Andrade Simon,0,"Canada, EUA, UK",4,2,3,3,2,3,...,1,1,2,3,1,3,2,3,2,3
134,2018-09-07 15:14:07.922,Tadeu Lopes Matos,0,"Canada, EUA",4,4,3,3,1,2,...,3,2,2,2,1,2,1,3,2,3
135,2018-04-03 22:36:46.198,Tales Foryta Jacoski,0,"Canada, EUA",4,1,3,1,1,2,...,2,1,2,4,1,2,1,3,3,2
136,2018-03-09 18:20:52.261,Thais Mitsuda Chagas,0,"Canada, EUA",1,1,3,3,2,3,...,1,1,2,4,1,3,1,1,1,3
137,2018-03-01 22:10:59.092,Valentina Rosset,0,EUA,1,1,3,2,3,2,...,1,2,2,2,2,3,3,3,2,3
138,2018-03-06 20:23:46.381,Victor Haysser Nardini Simões,0,"Canada, EUA, UK",4,2,3,1,2,1,...,1,2,3,4,1,1,3,3,2,3
139,2018-10-24 17:32:26.830,Victoria de Assis Torrentes,0,"Canada, EUA, UK",4,1,3,2,3,3,...,1,1,4,2,1,3,1,3,2,3
140,2018-08-14 10:54:42.289,Vinicius Gabriel Angelozzi Verona de Resende,0,"Canada, EUA, UK",1,1,4,1,2,2,...,3,2,1,1,1,2,1,3,2,2
141,2018-06-10 21:55:52.714,Vinícius Martins Ouverney dos Santos,0,"Canada, EUA",4,4,4,1,2,2,...,2,2,3,3,1,1,2,3,1,2
142,2018-05-15 16:41:47.957,Vitor Magalhães Lamego,1,"Canada, EUA",1,1,3,1,1,2,...,1,1,3,4,1,1,1,1,1,2
143,2018-08-02 16:49:03.856,Vitor Minami Chiga,0,"Canada, EUA",4,2,3,2,3,2,...,1,3,2,4,1,2,3,3,2,3
144,2018-04-26 14:16:14.843,Vitória Ibias Flach,0,"Canada, EUA, UK",1,1,1,1,2,3,...,1,1,4,4,2,3,1,2,1,3
145,2018-11-06 14:21:30.716,Vitória Mendonça Siqueira,1,"Canada, EUA",1,1,2,1,2,3,...,2,1,3,4,1,3,1,3,3,3
146,2018-12-21 12:48:22.525,Vitoria Rodrigues Castillo,0,EUA,2,1,1,2,2,2,...,2,1,3,4,2,2,2,2,2,2
147,2018-10-04 12:24:20.272,Waldemar . Verdi Netto,0,"EUA, UK",1,1,3,3,2,2,...,2,1,1,2,2,3,3,1,2,3
148,2018-03-20 15:57:22.933,Xiao Yi Song,0,"Canada, EUA",1,1,3,1,2,3,...,1,1,3,4,1,3,1,2,3,3

In [126]:
a = sigmoid(1,1,4,1,4,1,1,2,1,2,2,2,1,2,1,3,2,3)
a

0.49588835268381976

In [113]:
Y_train

51     0
2      0
146    0
10     0
56     0
113    0
143    0
116    0
66     0
78     0
71     0
131    0
120    0
89     0
145    1
100    0
50     1
126    0
60     0
30     0
63     0
91     0
83     0
86     0
123    0
98     0
122    0
48     0
13     0
108    0
      ..
19     0
29     0
129    0
49     0
135    0
99     0
82     1
64     0
148    0
79     1
115    0
144    0
72     1
77     0
25     0
81     0
139    0
141    0
39     0
58     0
88     0
70     0
87     0
36     0
21     0
9      0
103    0
67     0
117    0
47     0
Name: Desistências, Length: 111, dtype: int64